# Generated by Django 4.0 on 2022-04-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ver_alter_post_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='profilePic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('pic', models.CharField(max_length=500)),
            ],
        ),
    ]
