# Generated by Django 4.0 on 2022-04-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Content',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
