# Generated by Django 4.0 on 2022-04-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_post_content_alter_post_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_pk', models.BigIntegerField()),
                ('Comment', models.CharField(max_length=100)),
            ],
        ),
    ]
