# Generated by Django 4.0 on 2022-04-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_comment_date_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='notificationsmLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myuser', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('to_pk', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='notificationsmMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('to_pk', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='to_pk',
            field=models.BigIntegerField(blank=True),
        ),
    ]
