# Generated by Django 4.0 on 2022-04-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_notificationsmlike_notificationsmmention_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsmmention',
            name='myuser',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
