# Generated by Django 4.0 on 2022-04-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_notificationsmmention_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsmmention',
            name='date',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
