# Generated by Django 4.0 on 2022-04-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_notificationsmmention_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
