# Generated by Django 4.0 on 2022-04-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_profilepic_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='pic',
            field=models.CharField(max_length=100),
        ),
    ]
