# Generated by Django 4.0 on 2022-04-11 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_profilepic_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Comment',
            new_name='Content',
        ),
    ]
