# Generated by Django 4.0 on 2022-04-14 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_notificationsmmention_options_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
