# Generated by Django 4.0 on 2022-05-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_post_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='clicked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_pk', models.CharField(max_length=100)),
                ('click', models.IntegerField()),
                ('date', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
